version: '3'
services:
  blog:
    image: amaslak0v/blog:0.1
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=amaslakov.com

# https://github.com/jwilder/nginx-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
