version: '3'
services:
  blog:
    #image: 025772230981.dkr.ecr.eu-central-1.amazonaws.com/blog
    image: amaslak0v/amaslakov.com:1.1
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=amaslakov.com

# https://github.com/jwilder/nginx-proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
