  - name: Create docker-compose file
    template:
      src: docker-compose.yml.j2
      dest: "{{ base_dir }}/docker-compose.yml"

# Pull & restart
  - name: Restart services
    docker_compose:
      project_src: "{{ base_dir }}"
      build: yes
      restarted: yes
    register: output
