---
tasks:

  - name: Create dir for https certs
    file:
      path: "{{ nginx_cert_dir }}"
      state: directory
      owner: root
      group: root

  - name: Copy certs
    copy:
      src: "{{ item }}"
      dest: "{{ nginx_cert_dir }}"
      owner: root
      group: root
      mode: '0600'
    with_fileglob:
     - ../files/certs/*

  - name: Create docker-compose file
    template:
      src: docker-compose.yml.j2
      dest: "{{base_dir}}/docker-compose.yml"
    notify:
    - restart containers

  - name: Create a DOS-style text file from a template
    template:
      src: docker-compose.yml.j2
      dest: /share/windows/config.ini
      newline_sequence: '\r\n'

  - name: Pull default Docker image
    docker_image:
      name: "{{ default_container_image }}"
      source: pull


  - name: Restart services
    docker_compose:
      project_src: flask
      build: no
      restarted: yes
    register: output
