---
- hosts: all
  become: true # Use root only for installation
  vars:
    docker_compose_pip_executable: pip3
    docker_compose_packages: python3-pip
    blog_image_name: amaslak0v/blog
    blog_image_version: ""
    blog_mail: amaslakov.com@gmail.com
    blog_domain: amaslakov.com

  roles:
    - role: galaxy-pip
      vars:
        pip_install_packages:
          - name: docker
          - name: docker-compose
      tags: [install]
    - role: galaxy-docker
      tags: [install]
    - role: blog-deployment
      tags: [install]
    - role: galaxy-certbot
      vars:
        certbot_create_if_missing: yes
        certbot_create_method: standalone
        certbot_admin_email: "{{ blog_mail }}"
        domains:
          - "{{ blog_domain }}"
        certbot_create_standalone_stop_services:
          - nginx
        tags: [install]
    - role: blog-deployment
      tags: [deploy]
